/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainUI.java
 *
 * Created on 03-Mar-2011, 12:10:12
 */

package princeui;

/**
 *
 * @author Sam
 */
public class MainUI extends javax.swing.JFrame {


    
    /** Creates new form MainUI */
    public MainUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        section = new javax.swing.JCheckBox();
        math = new javax.swing.JCheckBox();
        outName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pathPrince = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pathIndex = new javax.swing.JTextField();
        pathTheme = new javax.swing.JTextField();
        browseIndex = new javax.swing.JButton();
        browseCSS = new javax.swing.JButton();
        browsePrince = new javax.swing.JButton();
        convert = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Converter");
        setMinimumSize(new java.awt.Dimension(505, 324));
        setResizable(false);

        jLabel1.setText("Super Slides: HTML to PDF Converter");

        section.setSelected(mainWrapper.getReplaceSection());
        section.setText("Replace Section Tags");

        math.setSelected(mainWrapper.getConvertMath());
        math.setText("Convert LaTeX Math");

        outName.setEditable(false);
        outName.setText(mainWrapper.getOutName());

        jLabel2.setText("Output PDF Name:");

        jLabel3.setText("Prince exe Path:");

        pathPrince.setText(mainWrapper.getPrincePath());

        jLabel4.setText("SuperSlides Index File:");

        jLabel5.setText("Theme CSS:");

        pathIndex.setText(mainWrapper.getIndexPath());

        pathTheme.setEditable(false);
        pathTheme.setText("Please select when PrinceXML loads");

        browseIndex.setText("Browse");
        browseIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseIndexActionPerformed(evt);
            }
        });

        browseCSS.setText("Browse");
        browseCSS.setEnabled(false);
        browseCSS.setFocusable(false);
        browseCSS.setOpaque(false);
        browseCSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseCSSActionPerformed(evt);
            }
        });

        browsePrince.setText("Browse");
        browsePrince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browsePrinceActionPerformed(evt);
            }
        });

        convert.setText("Convert");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(math)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(section)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(44, 44, 44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pathPrince)
                                .addComponent(outName, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(pathTheme)
                                .addComponent(pathIndex))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(browseIndex)
                                .addComponent(browseCSS)
                                .addComponent(browsePrince)))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cancel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(convert))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(section)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(math)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pathPrince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsePrince))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pathIndex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseIndex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pathTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseCSS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convert)
                    .addComponent(cancel))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseFile(String postfixDescription, String postfix, java.awt.Component comp, javax.swing.JTextField link){
        int test;
        javax.swing.JFileChooser princeSelector = new javax.swing.JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filter = new javax.swing.filechooser.FileNameExtensionFilter(postfixDescription, postfix);
        princeSelector.setFileFilter(filter);
        test = princeSelector.showOpenDialog(comp);
        try{
            if(test == princeSelector.APPROVE_OPTION){
                System.out.println(princeSelector.getSelectedFile().getAbsolutePath());
                link.setText(princeSelector.getSelectedFile().getAbsolutePath());
            }
            else {
                return;
            }

        }
        catch (Exception e){
            System.out.println(e);
        }
        return;
    }

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        // TODO add your handling code here:
        mainWrapper.setOutName(outName.getText());
        mainWrapper.setIndexPath(pathIndex.getText());
        mainWrapper.setThemePath(pathTheme.getText());
        mainWrapper.setPrincePath(pathPrince.getText());
        mainWrapper.setReplaceSection(section.isSelected());
        mainWrapper.setConvertMath(math.isSelected());
        String [] tempArr;
        tempArr = pathIndex.getText().split("\\\\slides\\\\");
        System.out.println(tempArr[0]);
        System.out.println(tempArr.length);
        if(tempArr.length < 2)
        {
            javax.swing.JOptionPane.showMessageDialog(this,
             "Directory Structure not recognised as SuperSlides: Please make sure the selected file is contained within the 'slides' directory",
               "Directory Parsing Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);

        }
        else
        {
            mainWrapper.beginMain();
        }
    }//GEN-LAST:event_convertActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancelActionPerformed

    private void browsePrinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsePrinceActionPerformed
        // TODO add your handling code here:
        browseFile("Executable (*.exe)","exe",this, pathPrince);
    }//GEN-LAST:event_browsePrinceActionPerformed

    private void browseIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseIndexActionPerformed
        // TODO add your handling code here:
        browseFile("HTML file (*.html)", "html",this, pathIndex);
    }//GEN-LAST:event_browseIndexActionPerformed

    private void browseCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseCSSActionPerformed
        // TODO add your handling code here:
        browseFile("Cascading Style Sheet (*.css)", "css",this, pathTheme);
    }//GEN-LAST:event_browseCSSActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void runUI() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                   javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                }
                catch (Exception e){
                    //Do Nothing
                }
                new MainUI().setVisible(true);
            }
        });
    }

    private static Wrapper mainWrapper = new Wrapper();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseCSS;
    private javax.swing.JButton browseIndex;
    private javax.swing.JButton browsePrince;
    private javax.swing.JButton cancel;
    private javax.swing.JButton convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox math;
    private javax.swing.JTextField outName;
    private javax.swing.JTextField pathIndex;
    private javax.swing.JTextField pathPrince;
    private javax.swing.JTextField pathTheme;
    private javax.swing.JCheckBox section;
    // End of variables declaration//GEN-END:variables

}
